# Test making MSD tables based on lexicon and specifications
#### Still work in progress!!!
tst-exa1:
	head -1000 < ../mte-lex/lex-v6/wfl-sl.txt | bin/wfl2exa.pl 5 > tmp/msd-sl.wfl.txt
tst-exa2:
	cat < ../mte-lex/lex-v6/wfl-en.txt | bin/wfl2exa.pl 5 > tmp/msd-en.wfl.txt
	cat < ../mte-lex/lex-v6/wfl-sl.txt | bin/wfl2exa.pl 5 > tmp/msd-sl.wfl.txt
	bin/msd-index.pl en xml/msd-en.xml < tmp/msd-en.wfl.txt > tmp/msd-en.index.xml
	bin/msd-index.pl sl xml/msd-sl.xml < tmp/msd-sl.wfl.txt > tmp/msd-sl.index.xml

# Test generation of the feature-structure libraries
tst-fs:
	$s -xsl:bin/msd-fslib.xsl xml/msd-en.xml > tmp/fslib-en.xml
	$s -xsl:bin/check-links.xsl tmp/fslib-en.xml
	$s -xsl:bin/expand-fs.xsl tmp/fslib-en.xml > tmp/fslib2-en.xml
	$s -xsl:bin/msd-fslib.xsl xml/msd-sl.xml > tmp/fslib-sl.xml
	$s -xsl:bin/check-links.xsl tmp/fslib-sl.xml
	$s -xsl:bin/expand-fs.xsl tmp/fslib-sl.xml > tmp/fslib2-sl.xml

# Test generation of tables for a couple of languages
tst-tbls:
	bin/msd-tables.pl -specs xml/msd.xml -infiles xml/msd-en.xml -outdir tmp
	bin/msd-tables.pl -specs xml/msd.xml -infiles xml/msd-sl.xml -outdir tmp

# Take a L new language section and
# merge its features into the section with common tables
# Complains if this leads to errors
# Input L and output files should be in ./tmp/
L = sq
new:
	$s add=../tmp/msd-$L.xml -xsl:bin/msd-merge.xsl xml/msd.xml \
	> tmp/msd_with_$L.xml 2> tmp/msd-$L.log

nohup:
	nohup time make all > nohup.all &
all:	htm tbls
# Generate in parallel all the language tables
tbls:
	ls -d xml/msd-*.xml | parallel --gnu --halt 2 --jobs 20 \
	bin/msd-tables.pl -specs xml/msd.xml -infiles {} -outdir tables

# Make HTML version of the specifications
htm:
	rm -f html/*
	$s language=eng localisation=en -xsl:bin/teiHeader2html.xsl xml/msd.xml
	$s -xi -xsl:bin/msd-spec2prn.xsl xml/msd.xml | $s splitLevel=1 - -xsl:bin/msd-prn2html.xsl 
	cp html/msd.html html/index.html
	# for testing only
	rm -f /home/tomaz/WWW/tmp/mte/html/*; cp html/*.html /home/tomaz/WWW/tmp/mte/html

#STUB!
#xml-edit should have example lexica & autogenerated MSD index - this one should be then added into xml/*.xml
copy:
	cp xml-edit/*.xml xml

#XML validate TEI source
val:
	# $s -xi -xsl:bin/copy.xsl xml-edit/msd.xml | rnv schema/mte_tei.rnc
	$s -xi -xsl:bin/copy.xsl xml-edit/msd.xml | $j schema/mte_tei.rnc -

##############################################3
#Saxon for funny files (large text nodes, long UTF-8 chars
s = java -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAXParserFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl net.sf.saxon.Transform
#Default Saxon but doesn't show STDERR (<xsl:message>)
s = java -jar /usr/local/bin/saxon9he.jar
#This one does:
s = java -jar /home/tomaz/bin/saxon9he.jar
#Validation of TEI against RelaxNG schema
j = java -jar /usr/local/bin/jing.jar 
